testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to webMUSHRA!       
    - type: multi_metric_mushra
      id: trial1
      name: MUSHRA
      metrics:
          - MOS
          - S-MOS
          - N-MOS
      colors:
          - '#ED8C01'
          - '#007ACC'
          - '#2f9b5c'
      content:
          - "(MOS) This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition."
          - "(S-MOS) This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition."
          - "(N-MOS) This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition."
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
          - random
          - type: multi_metric_mushra
            id: trial_random_1
            name: MUSHRA - Random 2
            metrics:
                - MOS
                - S-MOS
                - N-MOS
            colors:
                - '#ED8C01'
                - '#007ACC'
                - '#2f9b5c'
            content:
                - (MOS) Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
                - (S-MOS) Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
                - (N-MOS) Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav          
          - type: multi_metric_mushra
            id: trial_random_2
            name: MUSHRA - Random 1
            metrics:
                - MOS
                - S-MOS
                - N-MOS
            colors:
                - '#ED8C01'
                - '#007ACC'
                - '#2f9b5c'
            content:
                - (MOS) Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
                - (S-MOS) Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
                - (N-MOS) Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav          
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
