bufferSize: 2048
language: en

loadOrigSR: true  # whether to additionally load each audio in its original sampling rate
pages:
# - type: generic_form
#   content: Welcome to speech data quality evaluation.<br/><br/>Please enter your <b>User Name</b> below and then click [Next] button to proceed.<br/><br/>
#   id: welcome
#   name: Speech data quality evaluation
#   questionnaire:
#   - label: User Name
#     name: participant_name
#     optional: false
#     type: text
#   - label: Passcode
#     name: participant_passcode
#     optional: false
#     type: password
#     minlength: 1
#     maxlength: 10
- type: generic
  id: welcome
  name: Speech data quality evaluation
  content: Welcome to speech data quality evaluation.<br/><br/>Please click [Next] button to proceed.<br/><br/>
- type: generic
  id: explanation
  name: Explanation
  content: 'In the following pages, you will be asked to listen to the given audio in each page, and check the corresponding spectrogram.
    Then rate the quality of the audio by selecting the best-matched tags.<br><br>Please click [Next] button to proceed.'
- type: wave_spec_tagging
  id: trial_tagging
  name: Speech Data Quality Evaluation (1/10)
  content: 'Listen to the given audio in each page, and check the corresponding spectrogram. Then rate the quality of the audio by selecting the best-matched tags.
  You can navigate to previous and next audios by clicking "&lt;" and "&gt;" buttons on the upper-left corner.'
  audioList: ../res/audios.tsv  # the first line must be header line
  shuffleAudio: false  # whether to randomly shuffle the audio loading order
  localMode: true  # [Warning: don't set to true when deploying in a remote server] If true, the web page is assumed to be deployed in the same local machine as the user will use
  localRootPath: "/Users/wangyouz/Desktop/webMUSHRA"  # Path to the root directory of this project (used only when localMode === true)
  labelCache: true  # If true, the browser's localStorage will be used for storing and loading labeled tags in the past
  showWaveform: true  # whether to display the waveform of each audio
  waveformColors:
    unselectedColor: '#808080'  # color of unselected audio looping regions (used when enableLooping === true)
    # notPlayedColor: '#F8DEBD'  # color of waveform parts that are not played yet
    # notPlayedColor: '#A03CC8'  # color of waveform parts that are not played yet
    notPlayedColor: '#DFC1EA'  # color of waveform parts that are not played yet
    playedColor: '#A03CC8'  # color of waveform parts that are already played
    cursorColor: '#3478C6'  # color of the cursor for indicating the current audio playing position
    sliderColor: '#ED8C01'  # override color of the noUiSlider (used when enableLooping === true)
  staticWaveform: true  # if false, the waveform will be refreshed during playing to reflect the player progress (this may cause laggy playing for long audios due to intensive computations); otherwise, the waveform will not be refreshed during playing (notPlayedColor will be ignored)
  showCursor: true  # whether to show a vertical cursor to indicate the current audio playing position
  showMetaInfo: true  # whether to additionally display meta info (e.g., utterance ID and info provided in the `audioList` file) of each audio
  showSpectrogram: true  # whether to display the spectrogram of each audio (the original sampling rate will be used if loadOrigSR === true)
  spectrogramOptions:
    freqScale: linear  # linear, log, or mel
    fixedDurationWinSize: false  # whether to adaptively adjust the window size according to the actual sample rate to keep the duration fixed
  enableLooping: true  # whether to show a scaler for adjusting the segment for looping
  autoLooping: false  # whether to replay from the beginning after playing is finished
  mustViewAllAudios: true  # whether to disable the next page button until all audios are tagged
  normalizeVolume: 0.9  # if not null, automatically rescale the volume of each audio so that its maximum absolute value is the specified value
  remoteService: service/tagIO.php  # used for TSV file reading and writing (don't change this value)
  tags: # tags defined in one line - [...] will be displayed in a row
    - group: 'Data source'  # name to disply for this group of tags
      names: ["high_intelligibility", "medium_intelligibility", "low_intelligibility", "real_recording", "simulated"]  # tag names in this group
      colors: ['#ED8C01', '#ED8C01', '#ED8C01', '#007ACC', '#007ACC', '#007ACC']  # color of each tag in this group
      descriptions: ["The speech content can be clearly heard (even with noise).", "The speech content can be understood by listening carefully.", "The speech content cannot be understood even when listening carefully.", "The audio is a real recording.", "The audio is simulated."]  # text to display for each tag when hovered
    - group: Speech styles
      names: ["reading_style", "spontaneous_style", "singing_voice"]
      colors: ['#A03CC8', '#A03CC8', '#A03CC8']
      descriptions: ["The audio contains reading-style speech.", "The audio contains spontaneous speech.", "The audio contains singing voices."]
    - group: Speaker attribute
      names: ["male", "female", "Nspk", "speech_overlap", "unison"]
      colors: ['#2f9b5c', '#2f9b5c', '#4c0c9f', '#4c0c9f', '#4c0c9f']
      descriptions: ["The voice sounds like a male speaker", "The voice sounds like a female speaker.", ">1 types of voices appear sequentially in the audio.", "There are overlapped voices in the audio.", "There is unison in the audio."]
    - group: Distortion and interference
      names: ["bandwidth_limitation", "clipping", "sound_effect", "music"]
      colors: ['#99302b', '#99302b', '#99302b', '#99302b']
      descriptions: ["Bandwidth limitation can be heard / seen from the spectrogram.", "Clipping can be heard / seen from the waveform", "Sound effects can be heard.", "Background music can be heard."]
    - group: Noise
      names: ["low_freq_noise", "high_freq_noise", "background_noise", "instantaneous_noise"]
      colors: ['#99302b', '#99302b', '#99302b', '#99302b']
      descriptions: ["Low-frequency narrow-band noise can be heard / seen from the spectrogram.", "High-frequency narrow-band noise can be heard / seen from the spectrogram.", "Wide-band background noise can be heard / seen from the spectrogram.", "Instantaneous noise can be heard / seen from the spectrogram."]
    - group: Reverberation
      names: ["weak_reverberation", "medium_reverberation", "strong_reverberation"]
      colors: ['#EA513A', '#EA513A', '#EA513A']
      descriptions: ["Weak reverberation exists in the audio.", "Medium-level reverberation exists in the audio.", "Strong reverberation exists in the audio."]
- type: finish
  name: Thank you
  content: Thank you for attending!
  popupContent: Your results were sent. Goodbye and have a nice day   
  showResults: true
  showErrors: true
  writeResults: true
  questionnaire:
    - type: text
      label: Name
      name: name
      optional: false
    - type: text
      label: Email
      name: email
      optional: true
      placeholder: optional
    - type: number
      label: Age
      name: age
      optional: true
      min: 0
      max: 100
      default: 30
    - type: likert
      name: gender
      label: Gender
      response:
      - value: female
        label: Female
      - value: male
        label: Male
      - value: non_binary
        label: Non-binary
      - value: prefer_not_to_say
        label: Prefer not to say
    - type: long_text
      label: Feedback
      name: feedback
      optional: true
      placeholder: optional
remoteService: service/tsvWrite.php
showButtonPreviousPage: true
stopOnErrors: true
testId: subjective_evalaution
testname: Subjective evaluation
